services:
  catalogue:
    build: ./catalogue
    image: rubiya32/catalogue:1.0.0
    container_name: catalogue
    depends_on:
    - mongodb
  mongodb:
    build: ./mongodb # it moves to mongodb directory
    image: rubiya32/mongodb:1.0.0 
    container_name: mongodb    
  user:
    build: ./user
    image: rubiya32/user:1.0.0
    container_name: user
    depends_on:
    - mongodb  
networks:
  default:
    driver: bridge
    name: roboshop
    external: false # if true, you need to create network manually    