services:
  catalogue:
    build: ./catalogue
    image: rubiya32/catalogue:1.0.0
    container_name: catalogue
    depends_on:
    - mongodb
  mongodb:
    build: ./mongodb # it moves to mongodb directory
    image: rubiya32/mongodb:1.0.0 
    container_name: mongodb    
  user:
    build: ./user
    image: rubiya32/user:1.0.0
    container_name: user
    depends_on:
    - mongodb  
  cart:
    build: ./cart
    image: rubiya32/cart:1.0.0
    container_name: cart
    depends_on:
    - redis
    - catalogue
  payment:
    build: ./payment
    image: rubiya32/payment:1.0.0
    container_name: payment
    environment:
      CART_HOST: "cart"
      CART_PORT: "8080"
      USER_HOST: "user"
      USER_PORT: "8080"
      AMQP_HOST: "rabbitmq"
      AMQP_USER: "roboshop"
      AMQP_PASS: "roboshop123"
    depends_on:
    - rabbitmq
    - cart
    - user
  shipping:
    build: ./shipping
    image: rubiya32/shipping:1.0.0
    container_name: shipping
    depends_on:
    - mysql
    - cart 
  redis:
    image: redis:7.0
    container_name: redis
  mysql:
    build: ./mysql
    image: rubiya32/mysql:1.0.0
    container_name: mysql
  rabbitmq:
    image: rabbitmq:3
    environment: 
      RABBITMQ_DEFAULT_USER: roboshop
      RABBITMQ_DEFAULT_PASS: roboshop123
    container_name: rabbitmq   
  frontend:
    build: ./frontend
    image: rubiya32/frontend:1.0.0
    container_name: frontend
    ports:
    - "80:80"
    depends_on:
    - catalogue
    - user
    - cart
    - shipping
    - payment    
networks:
  default:
    driver: bridge
    name: roboshop
    external: false # if true, you need to create network manually    